// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXtfcrFXApgWR2tnUypbcctj-CmXpXys',
    appId: '1:258341298116:web:95db3b055d7c8feec34e91',
    messagingSenderId: '258341298116',
    projectId: 'home-decor-app-b2d9a',
    authDomain: 'home-decor-app-b2d9a.firebaseapp.com',
    storageBucket: 'home-decor-app-b2d9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_KZSDvqRJ9337sL-hIBah9SvUXnHzta4',
    appId: '1:258341298116:android:a0595bf88470de56c34e91',
    messagingSenderId: '258341298116',
    projectId: 'home-decor-app-b2d9a',
    storageBucket: 'home-decor-app-b2d9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz2jiZd-SaVP5l8TlFzAjgLJmsU2AT2pI',
    appId: '1:258341298116:ios:d7712c9bb5710eb3c34e91',
    messagingSenderId: '258341298116',
    projectId: 'home-decor-app-b2d9a',
    storageBucket: 'home-decor-app-b2d9a.appspot.com',
    iosBundleId: 'com.example.homedocorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz2jiZd-SaVP5l8TlFzAjgLJmsU2AT2pI',
    appId: '1:258341298116:ios:d7712c9bb5710eb3c34e91',
    messagingSenderId: '258341298116',
    projectId: 'home-decor-app-b2d9a',
    storageBucket: 'home-decor-app-b2d9a.appspot.com',
    iosBundleId: 'com.example.homedocorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXtfcrFXApgWR2tnUypbcctj-CmXpXys',
    appId: '1:258341298116:web:4b1120476de791bac34e91',
    messagingSenderId: '258341298116',
    projectId: 'home-decor-app-b2d9a',
    authDomain: 'home-decor-app-b2d9a.firebaseapp.com',
    storageBucket: 'home-decor-app-b2d9a.appspot.com',
  );
}
